#!/bin/bash -e

# node
grpc_tools_node_protoc \
    --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` \
    -I=$GOPATH/src/github.com/mesg-foundation/core/protobuf/coreapi/ api.proto \
    --js_out=import_style=commonjs,binary:./node \
    --grpc_out=./node 

# web
protoc \
    --plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts \
    -I=$GOPATH/src/github.com/mesg-foundation/core/protobuf/coreapi/ api.proto \
    --js_out=import_style=commonjs,binary:./web \
    --ts_out=service=true:./web